# Generated by Django 4.1.5 on 2023-01-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('core', '0002_bot_alter_chats_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('detalhada', models.TextField()),
                ('nome_responsavel', models.CharField(default='', max_length=100)),
                ('tel_responsavel', models.CharField(default='', max_length=100)),
                ('foto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
            ],
        ),
    ]
