# Generated by Django 4.1.5 on 2023-01-19 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empreendimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimentos',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimentos',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
