# Generated by Django 4.1.5 on 2023-01-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('core', '0006_usuario_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(default='', max_length=100)),
                ('instagram', models.CharField(default='', max_length=100)),
                ('youtube', models.CharField(default='', max_length=100)),
                ('foto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('link', models.TextField()),
                ('foto', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
            ],
        ),
        migrations.DeleteModel(
            name='bot',
        ),
        migrations.RemoveField(
            model_name='empreendimentos',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='empreendimentos',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='status',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='recados',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
        migrations.DeleteModel(
            name='Empreendimentos',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
