# Generated by Django 4.1.5 on 2023-01-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_usuario_banner_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='foto1',
            new_name='foto',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='foto2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='foto3',
        ),
    ]
