# Generated by Django 4.1.5 on 2023-01-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('core', '0009_rename_foto1_banner_foto_remove_banner_foto2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='saq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(default='', max_length=100)),
                ('pergunta', models.CharField(default='', max_length=100)),
                ('resposta', models.TextField()),
                ('foto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
            ],
        ),
    ]
