# Generated by Django 4.1.5 on 2023-01-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_acoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='curso',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dolar',
            name='curso',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indice',
            name='curso',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
